/**
 * Report Generator Utility
 * Generates CSV exports and professional HTML/PDF reports
 * - Worker Summary Report (hajari, expenses, payments, remaining)
 * - Material Summary Report (stock, usage, payments)
 * - Budget Overview Report (grand totals per site)
 * - Payment History Report
 */

import * as store from '@/lib/storage';
import { File as ExpoFile, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { formatCurrency } from './calculations';
import type { Worker, Material } from '@/lib/types';

// ═══════════════════════════════════ SHARED HTML HELPERS ═══════════════════════════════════

const fmt = (n: number) => `₹ ${n.toLocaleString('en-IN')}`;

function htmlShell(title: string, siteName: string, accentColor: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${title}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background:#f8fafc; color:#1e293b; padding:0; }
  .header { background: linear-gradient(135deg, ${accentColor}, ${darken(accentColor)}); color:#fff; padding:28px 32px 22px; }
  .header h1 { font-size:22px; font-weight:700; margin-bottom:4px; }
  .header .sub { font-size:12px; opacity:0.85; }
  .header .site-badge { display:inline-block; background:rgba(255,255,255,0.2); border-radius:6px; padding:3px 10px; font-size:11px; margin-top:8px; }
  .content { padding:24px 32px 32px; }
  .summary-row { display:flex; gap:12px; margin-bottom:20px; flex-wrap:wrap; }
  .stat-card { flex:1; min-width:120px; background:#fff; border-radius:12px; padding:16px; box-shadow:0 1px 3px rgba(0,0,0,0.08); border:1px solid #e2e8f0; }
  .stat-card .label { font-size:11px; color:#64748b; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:4px; }
  .stat-card .value { font-size:20px; font-weight:700; color:${accentColor}; }
  .stat-card .value.danger { color:#ef4444; }
  .stat-card .value.success { color:#10b981; }
  .section-title { font-size:14px; font-weight:700; color:#334155; margin:24px 0 10px; padding-bottom:6px; border-bottom:2px solid ${accentColor}; display:inline-block; }
  table { width:100%; border-collapse:collapse; margin-bottom:16px; background:#fff; border-radius:10px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,0.06); }
  thead th { background:${accentColor}; color:#fff; padding:10px 12px; font-size:11px; font-weight:600; text-align:left; text-transform:uppercase; letter-spacing:0.3px; white-space:nowrap; }
  tbody td { padding:9px 12px; font-size:12px; border-bottom:1px solid #f1f5f9; }
  tbody tr:nth-child(even) { background:#f8fafc; }
  tbody tr:hover { background:#f0f9ff; }
  .total-row td { font-weight:700; background:#f0f9ff !important; border-top:2px solid ${accentColor}; color:${accentColor}; font-size:12px; }
  .text-right { text-align:right; }
  .text-center { text-align:center; }
  .badge { display:inline-block; padding:2px 8px; border-radius:10px; font-size:10px; font-weight:600; }
  .badge-green { background:#dcfce7; color:#16a34a; }
  .badge-red { background:#fee2e2; color:#dc2626; }
  .badge-blue { background:#dbeafe; color:#2563eb; }
  .badge-yellow { background:#fef9c3; color:#ca8a04; }
  .footer { text-align:center; padding:20px; color:#94a3b8; font-size:10px; border-top:1px solid #e2e8f0; margin-top:16px; }
  .empty-msg { text-align:center; padding:40px; color:#94a3b8; font-size:14px; }
  @media print { body { background:#fff; } .content { padding:16px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="sub">Generated: ${new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' })} at ${new Date().toLocaleTimeString('en-IN', { hour:'2-digit', minute:'2-digit' })}</div>
    <div class="site-badge">📍 ${siteName}</div>
  </div>
  <div class="content">
    ${body}
  </div>
  <div class="footer">Generated by <strong>SiteLy</strong> — Construction Site Management App</div>
</body>
</html>`;
}

function darken(hex: string): string {
  const c = hex.replace('#', '');
  const r = Math.max(0, parseInt(c.substring(0, 2), 16) - 30);
  const g = Math.max(0, parseInt(c.substring(2, 4), 16) - 30);
  const b = Math.max(0, parseInt(c.substring(4, 6), 16) - 30);
  return `#${r.toString(16).padStart(2,'0')}${g.toString(16).padStart(2,'0')}${b.toString(16).padStart(2,'0')}`;
}

// ═══════════════════════════════════ CSV GENERATORS ═══════════════════════════════════

// ── Worker Report CSV ────────────────────────────────────────────────
export async function generateWorkerReportCSV(siteId: string, siteName: string): Promise<string> {
  const workers = await store.getWorkers(siteId);
  const lines: string[] = [
    `Site: ${siteName}`,
    `Date: ${new Date().toLocaleDateString()}`,
    '',
    'No.,Worker Name,Category,Total Hajari,Total Expense,Total Paid,Remaining',
  ];

  let grandHajari = 0, grandExpense = 0, grandPaid = 0, grandRemaining = 0;

  for (let i = 0; i < workers.length; i++) {
    const w = workers[i];
    const totals = await store.getWorkerTotals(siteId, w.id);
    grandHajari += totals.totalHajari;
    grandExpense += totals.totalExpense;
    grandPaid += totals.totalPaid;
    grandRemaining += totals.remaining;
    lines.push(`${i + 1},"${w.name}",${w.category},${totals.totalHajari},${totals.totalExpense},${totals.totalPaid},${totals.remaining}`);
  }

  lines.push('');
  lines.push(`TOTAL,,,${grandHajari},${grandExpense},${grandPaid},${grandRemaining}`);
  return lines.join('\n');
}

// ── Material Report CSV ──────────────────────────────────────────────
export async function generateMaterialReportCSV(siteId: string, siteName: string): Promise<string> {
  const materials = await store.getMaterials(siteId);
  const lines: string[] = [
    `Site: ${siteName}`,
    `Date: ${new Date().toLocaleDateString()}`,
    '',
    'No.,Material,Vendor,Qty,Unit,Rate/Unit,Total,Paid,Remaining Payment,Used Qty,Remaining Stock',
  ];

  let grandTotal = 0, grandPaid = 0, grandRemaining = 0;

  for (let i = 0; i < materials.length; i++) {
    const m = materials[i];
    const remaining = (m.totalAmount || 0) - (m.amountPaid || 0);
    grandTotal += m.totalAmount || 0;
    grandPaid += m.amountPaid || 0;
    grandRemaining += remaining;
    const usages = await store.getMaterialUsages(siteId, m.id);
    const totalUsed = usages.reduce((sum, u) => sum + (u.quantityUsed || 0), 0);
    const remainingStock = (m.quantity || 0) - totalUsed;
    lines.push(`${i + 1},"${m.name}","${m.vendorName || ''}",${m.quantity || 0},${m.unit || ''},${m.ratePerUnit || 0},${m.totalAmount || 0},${m.amountPaid || 0},${remaining},${totalUsed},${remainingStock}`);
  }

  lines.push('');
  lines.push(`TOTAL,,,,,,,${grandTotal},${grandPaid},${grandRemaining},,`);
  return lines.join('\n');
}

// ── Budget Overview CSV ──────────────────────────────────────────────
export async function generateBudgetReportCSV(siteId: string, siteName: string): Promise<string> {
  const workers = await store.getWorkers(siteId);
  const materials = await store.getMaterials(siteId);

  let totalWorkerHajari = 0, totalWorkerExpense = 0, totalWorkerPaid = 0, totalWorkerRemaining = 0;
  for (const w of workers) {
    const totals = await store.getWorkerTotals(siteId, w.id);
    totalWorkerHajari += totals.totalHajari;
    totalWorkerExpense += totals.totalExpense;
    totalWorkerPaid += totals.totalPaid;
    totalWorkerRemaining += totals.remaining;
  }

  let totalMaterialCost = 0, totalMaterialPaid = 0;
  materials.forEach((m: Material) => {
    totalMaterialCost += m.totalAmount || 0;
    totalMaterialPaid += m.amountPaid || 0;
  });
  const totalMaterialRemaining = totalMaterialCost - totalMaterialPaid;
  const grandTotalExpense = totalWorkerHajari + totalWorkerExpense + totalMaterialCost;
  const grandTotalPaid = totalWorkerPaid + totalMaterialPaid;
  const grandTotalRemaining = totalWorkerRemaining + totalMaterialRemaining;

  const lines: string[] = [
    `BUDGET REPORT - ${siteName}`,
    `Generated: ${new Date().toLocaleString()}`,
    '',
    'Category,Amount',
    '',
    'WORKER EXPENSES,',
    `Worker Hajari (Attendance),${totalWorkerHajari}`,
    `Worker Other Expenses,${totalWorkerExpense}`,
    `Total Worker Cost,${totalWorkerHajari + totalWorkerExpense}`,
    `Total Worker Paid,${totalWorkerPaid}`,
    `Worker Remaining Payment,${totalWorkerRemaining}`,
    '',
    'MATERIAL EXPENSES,',
    `Total Material Cost,${totalMaterialCost}`,
    `Total Material Paid,${totalMaterialPaid}`,
    `Material Remaining Payment,${totalMaterialRemaining}`,
    '',
    'GRAND TOTALS,',
    `Grand Total Expense,${grandTotalExpense}`,
    `Grand Total Paid,${grandTotalPaid}`,
    `Grand Remaining,${grandTotalRemaining}`,
    '',
    'SUMMARY,',
    `Total Workers,${workers.length}`,
    `Total Materials,${materials.length}`,
  ];

  return lines.join('\n');
}

// ── Payment History CSV ──────────────────────────────────────────────
export async function generatePaymentHistoryCSV(siteId: string, siteName: string): Promise<string> {
  const workerCSV = await store.getPaymentHistoryCSV(siteId);
  const materials = await store.getMaterials(siteId);
  const matLines: string[] = [
    '',
    'MATERIAL PAYMENTS',
    'No.,Material,Vendor,Total,Paid,Remaining,Date',
  ];
  let matGrandTotal = 0, matGrandPaid = 0;
  materials.forEach((m: Material, i: number) => {
    const remaining = (m.totalAmount || 0) - (m.amountPaid || 0);
    matGrandTotal += m.totalAmount || 0;
    matGrandPaid += m.amountPaid || 0;
    matLines.push(`${i + 1},"${m.name}","${m.vendorName || ''}",${m.totalAmount || 0},${m.amountPaid || 0},${remaining},${m.purchasedAt || ''}`);
  });
  matLines.push('');
  matLines.push(`TOTAL,,,${matGrandTotal},${matGrandPaid},${matGrandTotal - matGrandPaid},`);
  return workerCSV + '\n' + matLines.join('\n');
}

// ═══════════════════════════════════ HTML GENERATORS (FOR PDF) ═══════════════════════════════════

// ── Worker Report HTML ───────────────────────────────────────────────
export async function generateWorkerReportHTML(siteId: string, siteName: string): Promise<string> {
  const workers = await store.getWorkers(siteId);
  if (workers.length === 0) return '';

  let grandHajari = 0, grandExpense = 0, grandPaid = 0, grandRemaining = 0;
  const workerData: { w: Worker; totals: { totalHajari: number; totalExpense: number; totalPaid: number; remaining: number } }[] = [];

  for (const w of workers) {
    const totals = await store.getWorkerTotals(siteId, w.id);
    grandHajari += totals.totalHajari;
    grandExpense += totals.totalExpense;
    grandPaid += totals.totalPaid;
    grandRemaining += totals.remaining;
    workerData.push({ w, totals });
  }

  const rows = workerData.map((d, i) => `
    <tr>
      <td class="text-center">${i + 1}</td>
      <td><strong>${d.w.name}</strong></td>
      <td><span class="badge badge-blue">${d.w.category || 'General'}</span></td>
      <td class="text-right">${fmt(d.totals.totalHajari)}</td>
      <td class="text-right">${fmt(d.totals.totalExpense)}</td>
      <td class="text-right">${fmt(d.totals.totalPaid)}</td>
      <td class="text-right" style="color:${d.totals.remaining > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">
        ${fmt(d.totals.remaining)}
      </td>
    </tr>`).join('');

  const body = `
    <div class="summary-row">
      <div class="stat-card">
        <div class="label">Total Workers</div>
        <div class="value">${workers.length}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Hajari</div>
        <div class="value">${fmt(grandHajari)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Paid</div>
        <div class="value success">${fmt(grandPaid)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Remaining</div>
        <div class="value danger">${fmt(grandRemaining)}</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:40px;">#</th>
          <th>Worker Name</th>
          <th>Category</th>
          <th class="text-right">Hajari (₹)</th>
          <th class="text-right">Expense (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr class="total-row">
          <td></td>
          <td colspan="2"><strong>TOTAL</strong></td>
          <td class="text-right">${fmt(grandHajari)}</td>
          <td class="text-right">${fmt(grandExpense)}</td>
          <td class="text-right">${fmt(grandPaid)}</td>
          <td class="text-right">${fmt(grandRemaining)}</td>
        </tr>
      </tbody>
    </table>`;

  return htmlShell('Workers Report', siteName, '#0EA5E9', body);
}

// ── Material Report HTML ─────────────────────────────────────────────
export async function generateMaterialReportHTML(siteId: string, siteName: string): Promise<string> {
  const materials = await store.getMaterials(siteId);
  if (materials.length === 0) return '';

  let grandTotal = 0, grandPaid = 0, grandRemaining = 0;
  const matData: { m: Material; usedQty: number; remainingStock: number; remainingPayment: number }[] = [];

  for (const m of materials) {
    const remaining = (m.totalAmount || 0) - (m.amountPaid || 0);
    grandTotal += m.totalAmount || 0;
    grandPaid += m.amountPaid || 0;
    grandRemaining += remaining;
    const usages = await store.getMaterialUsages(siteId, m.id);
    const totalUsed = usages.reduce((sum, u) => sum + (u.quantityUsed || 0), 0);
    const remainingStock = (m.quantity || 0) - totalUsed;
    matData.push({ m, usedQty: totalUsed, remainingStock, remainingPayment: remaining });
  }

  const rows = matData.map((d, i) => `
    <tr>
      <td class="text-center">${i + 1}</td>
      <td><strong>${d.m.name}</strong></td>
      <td>${d.m.vendorName || '—'}</td>
      <td class="text-right">${d.m.quantity || 0} ${d.m.unit || ''}</td>
      <td class="text-right">${fmt(d.m.ratePerUnit || 0)}</td>
      <td class="text-right">${fmt(d.m.totalAmount || 0)}</td>
      <td class="text-right" style="color:#16a34a;">${fmt(d.m.amountPaid || 0)}</td>
      <td class="text-right" style="color:${d.remainingPayment > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">${fmt(d.remainingPayment)}</td>
      <td class="text-center">${d.usedQty} ${d.m.unit || ''}</td>
      <td class="text-center" style="color:${d.remainingStock <= 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">
        ${d.remainingStock} ${d.m.unit || ''}
      </td>
    </tr>`).join('');

  const body = `
    <div class="summary-row">
      <div class="stat-card">
        <div class="label">Total Materials</div>
        <div class="value">${materials.length}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Cost</div>
        <div class="value">${fmt(grandTotal)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Paid</div>
        <div class="value success">${fmt(grandPaid)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Remaining</div>
        <div class="value danger">${fmt(grandRemaining)}</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:35px;">#</th>
          <th>Material</th>
          <th>Vendor</th>
          <th class="text-right">Qty</th>
          <th class="text-right">Rate/Unit</th>
          <th class="text-right">Total (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
          <th class="text-center">Used</th>
          <th class="text-center">Stock Left</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr class="total-row">
          <td></td>
          <td colspan="4"><strong>TOTAL</strong></td>
          <td class="text-right">${fmt(grandTotal)}</td>
          <td class="text-right">${fmt(grandPaid)}</td>
          <td class="text-right">${fmt(grandRemaining)}</td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>`;

  return htmlShell('Materials Report', siteName, '#10B981', body);
}

// ── Budget Report HTML ───────────────────────────────────────────────
export async function generateBudgetReportHTML(siteId: string, siteName: string): Promise<string> {
  const workers = await store.getWorkers(siteId);
  const materials = await store.getMaterials(siteId);

  let totalWorkerHajari = 0, totalWorkerExpense = 0, totalWorkerPaid = 0, totalWorkerRemaining = 0;
  const workerRows: string[] = [];
  for (let i = 0; i < workers.length; i++) {
    const w = workers[i];
    const totals = await store.getWorkerTotals(siteId, w.id);
    totalWorkerHajari += totals.totalHajari;
    totalWorkerExpense += totals.totalExpense;
    totalWorkerPaid += totals.totalPaid;
    totalWorkerRemaining += totals.remaining;
    workerRows.push(`
      <tr>
        <td class="text-center">${i + 1}</td>
        <td>${w.name}</td>
        <td><span class="badge badge-blue">${w.category || 'General'}</span></td>
        <td class="text-right">${fmt(totals.totalHajari + totals.totalExpense)}</td>
        <td class="text-right">${fmt(totals.totalPaid)}</td>
        <td class="text-right" style="color:${totals.remaining > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">${fmt(totals.remaining)}</td>
      </tr>`);
  }
  const totalWorkerCost = totalWorkerHajari + totalWorkerExpense;

  let totalMaterialCost = 0, totalMaterialPaid = 0;
  const materialRows: string[] = [];
  for (let i = 0; i < materials.length; i++) {
    const m = materials[i];
    totalMaterialCost += m.totalAmount || 0;
    totalMaterialPaid += m.amountPaid || 0;
    const rem = (m.totalAmount || 0) - (m.amountPaid || 0);
    materialRows.push(`
      <tr>
        <td class="text-center">${i + 1}</td>
        <td>${m.name}</td>
        <td>${m.vendorName || '—'}</td>
        <td class="text-right">${fmt(m.totalAmount || 0)}</td>
        <td class="text-right">${fmt(m.amountPaid || 0)}</td>
        <td class="text-right" style="color:${rem > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">${fmt(rem)}</td>
      </tr>`);
  }
  const totalMaterialRemaining = totalMaterialCost - totalMaterialPaid;

  const grandTotalExpense = totalWorkerCost + totalMaterialCost;
  const grandTotalPaid = totalWorkerPaid + totalMaterialPaid;
  const grandTotalRemaining = totalWorkerRemaining + totalMaterialRemaining;

  const body = `
    <!-- Grand Summary Cards -->
    <div class="summary-row">
      <div class="stat-card">
        <div class="label">Grand Total Expense</div>
        <div class="value">${fmt(grandTotalExpense)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Paid</div>
        <div class="value success">${fmt(grandTotalPaid)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Remaining to Pay</div>
        <div class="value danger">${fmt(grandTotalRemaining)}</div>
      </div>
    </div>

    <!-- Overview Breakdown -->
    <table style="margin-bottom:24px;">
      <thead>
        <tr><th colspan="2" style="text-align:center; font-size:13px;">Budget Breakdown</th></tr>
      </thead>
      <tbody>
        <tr><td>👷 Worker Hajari (Attendance)</td><td class="text-right">${fmt(totalWorkerHajari)}</td></tr>
        <tr><td>💰 Worker Other Expenses</td><td class="text-right">${fmt(totalWorkerExpense)}</td></tr>
        <tr style="font-weight:700; background:#eff6ff;"><td>Total Worker Cost</td><td class="text-right" style="color:#0EA5E9;">${fmt(totalWorkerCost)}</td></tr>
        <tr><td>🧱 Total Material Cost</td><td class="text-right">${fmt(totalMaterialCost)}</td></tr>
        <tr style="font-weight:700; background:#f0fdf4;"><td>Total Paid (Workers + Materials)</td><td class="text-right" style="color:#16a34a;">${fmt(grandTotalPaid)}</td></tr>
        <tr style="font-weight:700; background:#fef2f2;"><td>Grand Remaining Payment</td><td class="text-right" style="color:#dc2626;">${fmt(grandTotalRemaining)}</td></tr>
        <tr><td>📊 Total Workers</td><td class="text-right">${workers.length}</td></tr>
        <tr><td>📦 Total Materials</td><td class="text-right">${materials.length}</td></tr>
      </tbody>
    </table>

    <!-- Worker Details Section -->
    <div class="section-title">👷 Worker Expenses (${workers.length})</div>
    ${workers.length > 0 ? `
    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:35px;">#</th>
          <th>Worker</th>
          <th>Category</th>
          <th class="text-right">Total Cost (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
        </tr>
      </thead>
      <tbody>
        ${workerRows.join('')}
        <tr class="total-row">
          <td></td>
          <td colspan="2"><strong>WORKER TOTAL</strong></td>
          <td class="text-right">${fmt(totalWorkerCost)}</td>
          <td class="text-right">${fmt(totalWorkerPaid)}</td>
          <td class="text-right">${fmt(totalWorkerRemaining)}</td>
        </tr>
      </tbody>
    </table>` : '<p class="empty-msg">No workers added yet</p>'}

    <!-- Material Details Section -->
    <div class="section-title">🧱 Material Expenses (${materials.length})</div>
    ${materials.length > 0 ? `
    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:35px;">#</th>
          <th>Material</th>
          <th>Vendor</th>
          <th class="text-right">Total Cost (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
        </tr>
      </thead>
      <tbody>
        ${materialRows.join('')}
        <tr class="total-row">
          <td></td>
          <td colspan="2"><strong>MATERIAL TOTAL</strong></td>
          <td class="text-right">${fmt(totalMaterialCost)}</td>
          <td class="text-right">${fmt(totalMaterialPaid)}</td>
          <td class="text-right">${fmt(totalMaterialRemaining)}</td>
        </tr>
      </tbody>
    </table>` : '<p class="empty-msg">No materials added yet</p>'}

    <!-- Grand Total Bar -->
    <div style="margin-top:24px; background:linear-gradient(135deg, #f59e0b, #d97706); border-radius:12px; padding:20px; color:#fff;">
      <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:12px;">
        <div>
          <div style="font-size:11px; opacity:0.85; text-transform:uppercase; letter-spacing:0.5px;">Grand Total Expense</div>
          <div style="font-size:24px; font-weight:700;">${fmt(grandTotalExpense)}</div>
        </div>
        <div style="text-align:center;">
          <div style="font-size:11px; opacity:0.85; text-transform:uppercase;">Total Paid</div>
          <div style="font-size:20px; font-weight:700;">${fmt(grandTotalPaid)}</div>
        </div>
        <div style="text-align:right;">
          <div style="font-size:11px; opacity:0.85; text-transform:uppercase;">Remaining</div>
          <div style="font-size:20px; font-weight:700;">${fmt(grandTotalRemaining)}</div>
        </div>
      </div>
    </div>`;

  return htmlShell('Budget Report', siteName, '#F59E0B', body);
}

// ── Payment History HTML ─────────────────────────────────────────────
export async function generatePaymentHistoryHTML(siteId: string, siteName: string): Promise<string> {
  const workers = await store.getWorkers(siteId);
  const materials = await store.getMaterials(siteId);

  // Worker payment rows
  let workerTotalPaid = 0;
  const wPayRows: string[] = [];
  let idx = 1;
  for (const w of workers) {
    const totals = await store.getWorkerTotals(siteId, w.id);
    if (totals.totalPaid > 0 || totals.remaining !== 0) {
      workerTotalPaid += totals.totalPaid;
      const totalDue = totals.totalHajari + totals.totalExpense;
      wPayRows.push(`
        <tr>
          <td class="text-center">${idx++}</td>
          <td><strong>${w.name}</strong></td>
          <td><span class="badge badge-blue">${w.category || 'General'}</span></td>
          <td class="text-right">${fmt(totalDue)}</td>
          <td class="text-right" style="color:#16a34a;">${fmt(totals.totalPaid)}</td>
          <td class="text-right" style="color:${totals.remaining > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">${fmt(totals.remaining)}</td>
        </tr>`);
    }
  }

  // Material payment rows
  let matTotalCost = 0, matTotalPaid = 0;
  const mPayRows: string[] = [];
  materials.forEach((m: Material, i: number) => {
    const rem = (m.totalAmount || 0) - (m.amountPaid || 0);
    matTotalCost += m.totalAmount || 0;
    matTotalPaid += m.amountPaid || 0;
    mPayRows.push(`
      <tr>
        <td class="text-center">${i + 1}</td>
        <td><strong>${m.name}</strong></td>
        <td>${m.vendorName || '—'}</td>
        <td class="text-right">${fmt(m.totalAmount || 0)}</td>
        <td class="text-right" style="color:#16a34a;">${fmt(m.amountPaid || 0)}</td>
        <td class="text-right" style="color:${rem > 0 ? '#dc2626' : '#16a34a'}; font-weight:600;">${fmt(rem)}</td>
        <td class="text-center">${m.purchasedAt || '—'}</td>
      </tr>`);
  });

  const grandPaid = workerTotalPaid + matTotalPaid;

  const body = `
    <div class="summary-row">
      <div class="stat-card">
        <div class="label">Worker Payments</div>
        <div class="value">${fmt(workerTotalPaid)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Material Payments</div>
        <div class="value">${fmt(matTotalPaid)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Paid</div>
        <div class="value success">${fmt(grandPaid)}</div>
      </div>
    </div>

    <!-- Worker Payments -->
    <div class="section-title">👷 Worker Payments</div>
    ${wPayRows.length > 0 ? `
    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:35px;">#</th>
          <th>Worker</th>
          <th>Category</th>
          <th class="text-right">Total Due (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
        </tr>
      </thead>
      <tbody>
        ${wPayRows.join('')}
      </tbody>
    </table>` : '<p class="empty-msg">No worker payments recorded</p>'}

    <!-- Material Payments -->
    <div class="section-title">🧱 Material Payments</div>
    ${mPayRows.length > 0 ? `
    <table>
      <thead>
        <tr>
          <th class="text-center" style="width:35px;">#</th>
          <th>Material</th>
          <th>Vendor</th>
          <th class="text-right">Total (₹)</th>
          <th class="text-right">Paid (₹)</th>
          <th class="text-right">Remaining (₹)</th>
          <th class="text-center">Date</th>
        </tr>
      </thead>
      <tbody>
        ${mPayRows.join('')}
        <tr class="total-row">
          <td></td>
          <td colspan="2"><strong>MATERIAL TOTAL</strong></td>
          <td class="text-right">${fmt(matTotalCost)}</td>
          <td class="text-right">${fmt(matTotalPaid)}</td>
          <td class="text-right">${fmt(matTotalCost - matTotalPaid)}</td>
          <td></td>
        </tr>
      </tbody>
    </table>` : '<p class="empty-msg">No material payments recorded</p>'}`;

  return htmlShell('Payment History', siteName, '#8B5CF6', body);
}

// ═══════════════════════════════════ SHARE/EXPORT ═══════════════════════════════════

export async function exportAndShareCSV(
  csvContent: string,
  filename: string
): Promise<void> {
  const file = new ExpoFile(Paths.cache, filename);
  file.write(csvContent);

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(file.uri, {
      mimeType: 'text/csv',
      dialogTitle: `Share ${filename}`,
      UTI: 'public.comma-separated-values-text',
    });
  }
}
